# Site settings
author: Daniel Sullivan
title: Sully Codes
header-img: img/home-bg.png
email: dansullivan19@gmail.com
copyright_name: Daniel Sullivan
description: > # this means to ignore newlines until "baseurl:"
  My Path into Programming
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  sullycodes

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
